# Configuration for Plant.png stippling (Figure 7c from paper)
image: "input/Plant.png"
algorithm: "ccvt"
points: 20000
output_dir: "output"
description: "CCVT stippling for Plant.png matching Figure 7c (20,000 points)"
